name : controlling execution flow

on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        type: boolean
        description: 'An example input for the workflow'
        default: true

jobs:
  example-job:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      