name : controlling workflow execution
on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        type: boolean
        description : 'whetehr unit test will pass or not'
        default: true
jobs:
  lint-build:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: run unit tests
        if: ${{ github.event.inputs.pass-unit-tests == 'true' }}
        run: echo "unit tests passed"
      