name: Print repo name

on:
  push:
    branches:
      - master  

jobs:
  Print-using-context:
    runs-on: [self-hosted,linux]
    if: ${{github.ref_name==master}}
    
    steps:
      - name: Print only when branch is master
        run: echo "I am currently on branch ${{github.ref_name }} so printing this"
        