name: Print name of github user using github context

on:
  push:
    branches:
      - master  

jobs:
  Print-name-using-context:
    runs-on: [self-hosted,linux]
    steps:
      - name: Print actor name
        run: echo "Triggered by ${{github.actor}}"
        